#服务提供者,相当于单体应用的dao层,注册服务到eureka服务器(类似IOC)
server:
  port: 8080
#注册服务,相当于写一个bean到容器,交由eureka服务器管理
spring:
  application:
    name: provider
#服务提供者的地址(现在demo采用本机作为服务提供者的地址)
eureka:
  instance:
    hostname: localhost
#配置服务的注册地址
    default-address-resolution-order: http://localhost:8761/eureka/
